### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by majutsushi** [ErgoDox-EZ/fusion#11]
I'm having some trouble getting this to work locally. Note that I have next to no experience with node/npm, so this may be a simple issue for all I know. This is on Debian unstable with the latest official nodejs package.

```
$ npm install gulp -g
/home/user/jan/.local/bin/gulp -> /home/user/jan/.local/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /home/user/jan/.local/lib/node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── v8flags@2.0.10 (user-home@1.1.1)
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, glob-watcher@0.0.6, glob-stream@3.1.18)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, fancy-log@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, gulplog@1.0.0, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
```
I assume that means that the command worked, but the output isn't exactly very helpful in that regard.

The next command does not fare so well:
```
$ npm install
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN deprecated reverend@0.2.0: supplanted by path-to-regexp@v1.1.0#compile
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:51:11)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at TunnelingAgent.exports.request (https.js:163:15)
npm ERR!     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:133:16)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at Object.exports.request (https.js:163:15)
npm ERR!     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.2.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/jan/src/ergodox/fusion
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
\
> utf-8-validate@1.2.1 install /home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/jan/src/ergodox/fusion/npm-debug.log
npm ERR! not ok code 0
```
The output is again rather ambiguous, but it looks like the only actual error is with an optional dependency, so I try starting node:
```
$ npm start

> fusion@1.0.0 start /home/user/jan/src/ergodox/fusion
> gulp serve

module.js:339
    throw err;
    ^

Error: Cannot find module 'xmlhttprequest'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/index.js:5:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! fusion@1.0.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fusion@1.0.0 start script.
npm ERR! This is most likely a problem with the fusion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusion
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/user/jan/src/ergodox/fusion
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/jan/src/ergodox/fusion/npm-debug.log
npm ERR! not ok code 0
```
Well, that didn't work. I try installing the `xmlhttprequest` module (which for some reason does *not* work if it is installed "globally"), but that just results in a message about a different module missing. So I install the additional modules `engine.io-parser`, `parseqs`, and `component-inherit` manually. This then leaves me with this message:
```
$ npm start

> fusion@1.0.0 start /home/user/jan/src/ergodox/fusion
> gulp serve

/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js:23
  var xhr = new XMLHttpRequest({ xdomain: false });
            ^

TypeError: XMLHttpRequest is not a function
    at /home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js:23:13
    at Object.<anonymous> (/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js:25:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/jan/src/ergodox/fusion/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:6:15)
    at Module._compile (module.js:435:26)

npm ERR! fusion@1.0.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fusion@1.0.0 start script.
npm ERR! This is most likely a problem with the fusion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusion
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/user/jan/src/ergodox/fusion
npm ERR! node -v v4.2.3
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/jan/src/ergodox/fusion/npm-debug.log
npm ERR! not ok code 0
```
And this is where I'm stuck. How do I get this to work? Thanks.

**Comment by tdegrunt** [comment]
Hi there,

Thanks for trying this, hope you are aware this is an unfinished product.
I'm hoping to get around finishing it soon actually. The idea is actually to turn this in an online service, whereby you configure the layout online and we just send you the firmware file.
Should be a lot easier to work with!

If you do still want to run it:
I've tested this with node v5.2.0 and npm version 3.3.12 on Mac OSX, but it should also work on debian of course.

There are some ubuntu/debian notes in the readme:
https://github.com/ErgoDox-EZ/fusion#ubuntu--debian

If you have any more trouble, let me know.

Cheers,
Tom

**Comment by majutsushi** [comment]
Ah, I didn't know that this was still work-in-progress. I did see the Debian notes, but since they are only talking about node version 4.x I assumed the official packages would be current enough. I think I'll just wait until it's finished then. Thanks, and feel free to close the issue!
